//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorMaintenance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\sqlexpress;Initial Catalog=Payables;Integrated Security=Tru" +
            "e")]
        public string PayablesConnectionString {
            get {
                return ((string)(this["PayablesConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NATHANPC\\SQLEXPRESS;Initial Catalog=\"D:\\5TSD - TEAM BASED SOFTWARE DE" +
            "VELOPMENT\\ASSIGNMENT\\ASSIGNMENT (PART 1)_V1_170318\\DATABASE FILES\\PAYABLES.MDF\";" +
            "Integrated Security=True")]
        public string D__5TSD___TEAM_BASED_SOFTWARE_DEVELOPMENT_ASSIGNMENT_ASSIGNMENT__PART_1__V1_170318_DATABASE_FILES_PAYABLES_MDFConnection {
            get {
                return ((string)(this["D__5TSD___TEAM_BASED_SOFTWARE_DEVELOPMENT_ASSIGNMENT_ASSIGNMENT__PART_1__V1_17031" +
                    "8_DATABASE_FILES_PAYABLES_MDFConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=Payables;Integrated Security=Tru" +
            "e")]
        public string PayablesConnectionString1 {
            get {
                return ((string)(this["PayablesConnectionString1"]));
            }
        }
    }
}
